networks:
  mynetwork:
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - mynetwork
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.4.4-ubuntu
    container_name: grafana
    networks:
      - mynetwork
    ports:
      - "3000:3000"

