version: '3.8'

networks:
  mynetwork:
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - mynetwork
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.4.4-ubuntu
    container_name: grafana
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_HOST=${GF_SMTP_HOST}

    volumes:
      - 'grafana_storage:/var/lib/grafana'
    networks:
      - mynetwork
    ports:
      - "3000:3000"

volumes:
  grafana_storage: {}

