version: '3.8'
services:
  # db:
  #   image: mysql:5.7
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example_root_password
  #     MYSQL_DATABASE: wordpress
  #     MYSQL_USER: wordpress
  #     MYSQL_PASSWORD: example_password

  wordpress:
    image: wordpress:latest
    ports:
      - '8002:80'
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=example_password
      - WORDPRESS_DB_NAME=wordpress
    # networks:
    #   - wordpress_network
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.api.rule=Host(`farsi.gizmoyab.com`)"
      - "traefik.http.services.api.loadbalancer.server.port=80"
      - "traefik.http.routers.api.entrypoints=web"
networks:
  proxy:
    external: true

# networks:
#   wordpress_network:
#     name: wordpress_network

volumes:
  db_data:
