version: "3.8"

services:
  mysql:
    image: mysql:8
    # container_name: mysql
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      # - MYSQL_ROOT_PASSWORD=rootpass123
      # - MYSQL_DATABASE=mysql-db
      # - MYSQL_USER=mysqluser
      # - MYSQL_PASSWORD=testpass123
      - MYSQL_ROOT_PASSWORD=example_root_password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=example_password
      # - MYSQL_TCP_PORT=3306
    networks:
      - wordpress-overlay-net

networks:
  wordpress-overlay-net:
    external: true

# networks:
#   wordpress_network:
#     name: wordpress_network

volumes:
  mysql_data: